### ISSUE TITLE
Example input file for masstodon_single()

### ISSUE THREAD

**Issue by ijmiller2** [MatteoLacki/masstodon#1]
Could you provide an example input file for the masstodon_single() method? We've progressed through a series of errors, but aren't having much luck getting it to work properly. 

Thank you for your support!

**Comment by MatteoLacki** [comment]
Hi,

sure, I will do it over the weekend!

*Mateusz Krzysztof Łącki*

*German tel. +49 159 01681376*
Polish tel. +48 579 647 311
Skype:   mathewin
GitHub: MatteoLacki <https://github.com/MatteoLacki>

**Comment by ijmiller2** [comment]
Great, thank you!

**Comment by MatteoLacki** [comment]
Hello, I updated a bit the readme file.
Also, when you install the module via the terminal, you can run 
```{bash}
masstodon -h
```
for a description of the parameters.

If it does not help, please send me more details about what's going wrong.

Best wishes,
Matteo

**Comment by MatteoLacki** [comment]
I am also working a bit on splitting the module into separate modules. This would be a version 2.0.
That's why I am a bit reluctant to go through the whole Sphinx generation of a proper manual (:

**Comment by ijmiller2** [comment]
Thanks, Matteo! I'll give it a try sometime early next week and let you know if I run into any further problems. From quick glance at the readme, I think you have addressed a number of our questions.
