### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ijmiller2** [MatteoLacki/masstodon#2]
Hey Matteo,

Still having a few issues running the masstodon_single() function. I'm able to load the example data structures okay, but getting an error when running the example code. I've attached a .pdf of my notebook with the error.

[masstodon_example.pdf](https://github.com/MatteoLacki/masstodon/files/2838726/masstodon_example.pdf)

Thanks in advance for your support,
Ian

**Comment by MatteoLacki** [comment]
Hello, OK, I can reproduce it on a fresh install from pip.
I am working on it.

*Mateusz Krzysztof Łącki*

*German tel. +49 159 01681376*
Polish tel. +48 579 647 311
Skype:   mathewin
GitHub: MatteoLacki <https://github.com/MatteoLacki>

**Comment by MatteoLacki** [comment]
Hi,

It seems that the version upload on pip is corrupted. I will fix it in the
evening.
For now, simply uninstall it with

> pip uninstall masstodon

and then install the version directly from git with

> pip install git+https://github.com/MatteoLacki/masstodon.git
>

Best!

*Mateusz Krzysztof Łącki*

*German tel. +49 159 01681376*
Polish tel. +48 579 647 311
Skype:   mathewin
GitHub: MatteoLacki <https://github.com/MatteoLacki>

**Comment by MatteoLacki** [comment]
I updated Pypi.
You no longer need to install directly from git, but do make sure that your
pip doesn't install the cached version of masstodon (i.e. version 0.15).
so, again:

> pip uninstall masstodon

pip install masstodon==0.16

should do the trick.

I am sorry for inconvenience.
I can only say, it worked locally :)

Cheers!


*Mateusz Krzysztof Łącki*

*German tel. +49 159 01681376*
Polish tel. +48 579 647 311
Skype:   mathewin
GitHub: MatteoLacki <https://github.com/MatteoLacki>

**Comment by ijmiller2** [comment]
Thanks for the quick response!

This got rid of the error for me.
```
pip uninstall masstodon
pip install masstodon==0.16
```
And I'm now getting the all output (including Plotly chart) from the example code.

Thanks again!

-Ian

**Comment by MatteoLacki** [comment]
My great pleasure to be of help.

*Mateusz Krzysztof Łącki*

*German tel. +49 159 01681376*
Polish tel. +48 579 647 311
Skype:   mathewin
GitHub: MatteoLacki <https://github.com/MatteoLacki>
